
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.sound.sampled.LineUnavailableException;
import javax.sound.sampled.UnsupportedAudioFileException;

public class HomePageForm extends javax.swing.JFrame {

    boolean clicked = false;
    AudioInputStream audioInputStream;
    Clip clip = AudioSystem.getClip();

    /**
     * Creates new form HomePageForm
     */
    public HomePageForm() throws LineUnavailableException, IOException, UnsupportedAudioFileException {
        initComponents();
        
//        audioInputStream = AudioSystem.getAudioInputStream(new File("src/audio/homeAudio.wav").getAbsoluteFile());
        audioInputStream = AudioSystem.getAudioInputStream(getClass().getResource("/audio/homeAudio.wav"));
        clip.open(audioInputStream);
        backgroundMusic();
    }

    public void backgroundMusic() {

        if (clicked == false) {
            clip.start();
            clip.loop(Clip.LOOP_CONTINUOUSLY);
        } else if (clicked == true) {
            clip.stop();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        playButton = new javax.swing.JButton();
        instructionsButton = new javax.swing.JButton();
        quitButton = new javax.swing.JButton();
        audio = new javax.swing.JButton();
        backgroundIMG = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("HOME");
        setMaximumSize(new java.awt.Dimension(650, 550));
        setPreferredSize(new java.awt.Dimension(650, 550));
        setResizable(false);
        getContentPane().setLayout(null);

        playButton.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        playButton.setText("PLAY");
        playButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 102), 2, true));
        playButton.setMargin(new java.awt.Insets(2, 1, 2, 14));
        playButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playButtonActionPerformed(evt);
            }
        });
        getContentPane().add(playButton);
        playButton.setBounds(40, 390, 160, 40);

        instructionsButton.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        instructionsButton.setText("INSTRUCTIONS");
        instructionsButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 102), 2, true));
        instructionsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                instructionsButtonActionPerformed(evt);
            }
        });
        getContentPane().add(instructionsButton);
        instructionsButton.setBounds(210, 390, 240, 40);

        quitButton.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        quitButton.setText("QUIT");
        quitButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 102), 2, true));
        quitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitButtonActionPerformed(evt);
            }
        });
        getContentPane().add(quitButton);
        quitButton.setBounds(460, 390, 160, 40);

        audio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/soundOn.jpg"))); // NOI18N
        audio.setPreferredSize(new java.awt.Dimension(45, 45));
        audio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                audioActionPerformed(evt);
            }
        });
        getContentPane().add(audio);
        audio.setBounds(10, 450, 45, 45);

        backgroundIMG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/homePageSmall.png"))); // NOI18N
        getContentPane().add(backgroundIMG);
        backgroundIMG.setBounds(0, 0, 650, 550);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void playButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playButtonActionPerformed
        try {
            IntroductionPageForm introduce = new IntroductionPageForm();
            introduce.setVisible(true);
            clip.close();
            dispose();
        } catch (UnsupportedAudioFileException | IOException | LineUnavailableException ex) {
            Logger.getLogger(HomePageForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_playButtonActionPerformed

    private void quitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitButtonActionPerformed
        try {
            QuitPageForm quit = new QuitPageForm();
            quit.setVisible(true);
            clip.close();
            dispose();
        } catch (UnsupportedAudioFileException | IOException | LineUnavailableException ex) {
            Logger.getLogger(HomePageForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_quitButtonActionPerformed

    private void instructionsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_instructionsButtonActionPerformed
        try {
            InstructionsPageForm instruct = new InstructionsPageForm();
            instruct.setVisible(true);
            clip.close();
            dispose();
        } catch (UnsupportedAudioFileException | IOException | LineUnavailableException ex) {
            Logger.getLogger(HomePageForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_instructionsButtonActionPerformed

    private void audioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_audioActionPerformed
        // TODO add your handling code here:
        if (clicked) {
            audio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/soundOn.jpg")));
            clicked = false;
            backgroundMusic();

        } else {
            audio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/soundOff.jpg")));
            clicked = true;
            backgroundMusic();
        }
    }//GEN-LAST:event_audioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new HomePageForm().setVisible(true);
                } catch (LineUnavailableException ex) {
                    Logger.getLogger(HomePageForm.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IOException ex) {
                    Logger.getLogger(HomePageForm.class.getName()).log(Level.SEVERE, null, ex);
                } catch (UnsupportedAudioFileException ex) {
                    Logger.getLogger(HomePageForm.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton audio;
    private javax.swing.JLabel backgroundIMG;
    private javax.swing.JButton instructionsButton;
    private javax.swing.JButton playButton;
    private javax.swing.JButton quitButton;
    // End of variables declaration//GEN-END:variables
}
