
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.sound.sampled.LineUnavailableException;
import javax.sound.sampled.UnsupportedAudioFileException;

public class InstructionsPageForm extends javax.swing.JFrame {

    boolean clicked = false;
    AudioInputStream audioInputStream;
    Clip clip = AudioSystem.getClip();
    int pageNumber = 1;

    /**
     * Creates new form InstructionsPageForm
     */
    public InstructionsPageForm() throws UnsupportedAudioFileException, IOException, LineUnavailableException {
        initComponents();
        previousButton.setVisible(false);

        audioInputStream = AudioSystem.getAudioInputStream(getClass().getResource("/audio/waiting.wav"));
        clip.open(audioInputStream);
        backgroundMusic();
    }

    public void backgroundMusic() {

        if (clicked == false) {
            clip.start();
            clip.loop(Clip.LOOP_CONTINUOUSLY);
        } else if (clicked == true) {
            clip.stop();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        homeButton = new javax.swing.JButton();
        nextButton = new javax.swing.JButton();
        previousButton = new javax.swing.JButton();
        audio = new javax.swing.JButton();
        bgIMG1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("INSTRUCTIONS");
        setPreferredSize(new java.awt.Dimension(700, 600));
        setResizable(false);
        getContentPane().setLayout(null);

        homeButton.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        homeButton.setText("HOME");
        homeButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 102), 2, true));
        homeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeButtonActionPerformed(evt);
            }
        });
        getContentPane().add(homeButton);
        homeButton.setBounds(70, 30, 150, 40);

        nextButton.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        nextButton.setText("NEXT");
        nextButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 102), 2, true));
        nextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextButtonActionPerformed(evt);
            }
        });
        getContentPane().add(nextButton);
        nextButton.setBounds(510, 520, 150, 40);

        previousButton.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        previousButton.setText("PREVIOUS");
        previousButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 102), 2, true));
        previousButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                previousButtonActionPerformed(evt);
            }
        });
        getContentPane().add(previousButton);
        previousButton.setBounds(350, 520, 150, 40);

        audio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/soundOn.jpg"))); // NOI18N
        audio.setPreferredSize(new java.awt.Dimension(45, 45));
        audio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                audioActionPerformed(evt);
            }
        });
        getContentPane().add(audio);
        audio.setBounds(10, 510, 45, 45);

        bgIMG1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/instructionsPageSmall1(700x600).png"))); // NOI18N
        getContentPane().add(bgIMG1);
        bgIMG1.setBounds(0, 0, 700, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void homeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeButtonActionPerformed
        try {
            HomePageForm home = new HomePageForm();
            home.setVisible(true);
            clip.close();
            dispose();
        } catch (LineUnavailableException | IOException | UnsupportedAudioFileException ex) {
            Logger.getLogger(InstructionsPageForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_homeButtonActionPerformed

    private void previousButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_previousButtonActionPerformed
        if (pageNumber == 2) {
            pageNumber = 1;
            bgIMG1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/instructionsPageSmall1(700x600).png")));
            previousButton.setVisible(false);
        } else if (pageNumber == 3) {
            pageNumber = 2;
            bgIMG1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/instructionsPageSmall2(700x600).png")));
            nextButton.setVisible(true);
        }
    }//GEN-LAST:event_previousButtonActionPerformed

    private void nextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextButtonActionPerformed
        if (pageNumber == 1) {
            pageNumber = 2;
            bgIMG1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/instructionsPageSmall2(700x600).png")));
            previousButton.setVisible(true);
        } else if (pageNumber == 2) {
            pageNumber = 3;
            bgIMG1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/instructionsPageSmall3(700x600).png")));
            nextButton.setVisible(false);
        }
    }//GEN-LAST:event_nextButtonActionPerformed

    private void audioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_audioActionPerformed
        // TODO add your handling code here:
        if (clicked) {
            audio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/soundOn.jpg")));
            clicked = false;
            backgroundMusic();
        } else {
            audio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/soundOff.jpg")));
            clicked = true;
            backgroundMusic();
        }
    }//GEN-LAST:event_audioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new InstructionsPageForm().setVisible(true);
                } catch (UnsupportedAudioFileException | IOException | LineUnavailableException ex) {
                    Logger.getLogger(InstructionsPageForm.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton audio;
    private javax.swing.JLabel bgIMG1;
    private javax.swing.JButton homeButton;
    private javax.swing.JButton nextButton;
    private javax.swing.JButton previousButton;
    // End of variables declaration//GEN-END:variables
}
