
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.sound.sampled.LineUnavailableException;
import javax.sound.sampled.UnsupportedAudioFileException;

public class IntroductionPageForm extends javax.swing.JFrame {
    
    boolean clicked = false;
    AudioInputStream audioInputStream;
    Clip clip = AudioSystem.getClip();

    /**
     * Creates new form IntroductionPageForm
     */
    public IntroductionPageForm() throws UnsupportedAudioFileException, IOException, LineUnavailableException {
        initComponents();
        
        audioInputStream = AudioSystem.getAudioInputStream(getClass().getResource("/audio/transition.wav"));
        clip.open(audioInputStream);
        backgroundMusic();
    }
    
    public void backgroundMusic() {

        if (clicked == false) {
            clip.start();
            clip.loop(Clip.LOOP_CONTINUOUSLY);
        } else if (clicked == true) {
            clip.stop();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        continueButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        audio = new javax.swing.JButton();
        bgIMG = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("INTRODUCTIONS");
        setPreferredSize(new java.awt.Dimension(700, 600));
        setResizable(false);
        getContentPane().setLayout(null);

        continueButton.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        continueButton.setText("CONTINUE");
        continueButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 255), 2, true));
        continueButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                continueButtonActionPerformed(evt);
            }
        });
        getContentPane().add(continueButton);
        continueButton.setBounds(30, 420, 130, 30);

        cancelButton.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        cancelButton.setText("RETURN");
        cancelButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 102, 255), 2, true));
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });
        getContentPane().add(cancelButton);
        cancelButton.setBounds(30, 450, 130, 30);

        audio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/soundOn.jpg"))); // NOI18N
        audio.setPreferredSize(new java.awt.Dimension(45, 45));
        audio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                audioActionPerformed(evt);
            }
        });
        getContentPane().add(audio);
        audio.setBounds(10, 510, 45, 45);

        bgIMG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/introductionPageSmall(700x600).png"))); // NOI18N
        getContentPane().add(bgIMG);
        bgIMG.setBounds(0, 0, 700, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void continueButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_continueButtonActionPerformed
        SplashScreenForm game = new SplashScreenForm();
        game.setVisible(true);
        clip.close();
        dispose();
    }//GEN-LAST:event_continueButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        try {
            HomePageForm home = new HomePageForm();
            home.setVisible(true);
            clip.close();
            dispose();
        } catch (LineUnavailableException | IOException | UnsupportedAudioFileException ex) {
            Logger.getLogger(IntroductionPageForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void audioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_audioActionPerformed
        // TODO add your handling code here:
        if (clicked) {
            audio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/soundOn.jpg")));
            clicked = false;
            backgroundMusic();
        } else {
            audio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/soundOff.jpg")));
            clicked = true;
            backgroundMusic();
        }
    }//GEN-LAST:event_audioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new IntroductionPageForm().setVisible(true);
                } catch (UnsupportedAudioFileException | IOException | LineUnavailableException ex) {
                    Logger.getLogger(IntroductionPageForm.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton audio;
    private javax.swing.JLabel bgIMG;
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton continueButton;
    // End of variables declaration//GEN-END:variables
}
