
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.sound.sampled.LineUnavailableException;
import javax.sound.sampled.UnsupportedAudioFileException;

public class QuitPageForm extends javax.swing.JFrame {
    
    boolean clicked = false;
    AudioInputStream audioInputStream;
    Clip clip = AudioSystem.getClip();
    /**
     * Creates new form QuitPageForm
     */
    public QuitPageForm() throws UnsupportedAudioFileException, IOException, LineUnavailableException {
        initComponents();
        
        audioInputStream = AudioSystem.getAudioInputStream(getClass().getResource("/audio/ticky.wav"));
        clip.open(audioInputStream);
        backgroundMusic();
    }
    
    public void backgroundMusic() {

        if (clicked == false) {
            clip.start();
            clip.loop(Clip.LOOP_CONTINUOUSLY);
        } else if (clicked == true) {
            clip.stop();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        yesButton = new javax.swing.JButton();
        noButton = new javax.swing.JButton();
        audio = new javax.swing.JButton();
        backgroundIMG = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ARE YOU A QUITTER?!");
        setPreferredSize(new java.awt.Dimension(600, 550));
        setResizable(false);
        getContentPane().setLayout(null);

        yesButton.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        yesButton.setText("YES");
        yesButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 102), 2, true));
        yesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yesButtonActionPerformed(evt);
            }
        });
        getContentPane().add(yesButton);
        yesButton.setBounds(80, 420, 210, 40);

        noButton.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        noButton.setText("NO");
        noButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 102), 3, true));
        noButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noButtonActionPerformed(evt);
            }
        });
        getContentPane().add(noButton);
        noButton.setBounds(310, 420, 210, 40);

        audio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/soundOn.jpg"))); // NOI18N
        audio.setPreferredSize(new java.awt.Dimension(45, 45));
        audio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                audioActionPerformed(evt);
            }
        });
        getContentPane().add(audio);
        audio.setBounds(10, 460, 45, 45);

        backgroundIMG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/quitPageSmall(600x550).png"))); // NOI18N
        getContentPane().add(backgroundIMG);
        backgroundIMG.setBounds(0, 0, 600, 550);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void noButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noButtonActionPerformed
        try {
            HomePageForm home = new HomePageForm();
            home.setVisible(true);
            clip.stop();
            dispose();
        } catch (LineUnavailableException | IOException | UnsupportedAudioFileException ex) {
            Logger.getLogger(QuitPageForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_noButtonActionPerformed

    private void yesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yesButtonActionPerformed
        clip.stop();
        dispose();
        System.exit(0);
    }//GEN-LAST:event_yesButtonActionPerformed

    private void audioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_audioActionPerformed
        // TODO add your handling code here:
        if (clicked) {
            audio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/soundOn.jpg")));
            clicked = false;
            backgroundMusic();
        } else {
            audio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/soundOff.jpg")));
            clicked = true;
            backgroundMusic();
        }
    }//GEN-LAST:event_audioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new QuitPageForm().setVisible(true);
                } catch (UnsupportedAudioFileException | IOException | LineUnavailableException ex) {
                    Logger.getLogger(QuitPageForm.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton audio;
    private javax.swing.JLabel backgroundIMG;
    private javax.swing.JButton noButton;
    private javax.swing.JButton yesButton;
    // End of variables declaration//GEN-END:variables
}
